### PR TITLE
Promise issue

### PR DESCRIPTION
**Pull request by danielmhair**
While trying to populate over 100,000 documents using your module (which is great by the way), I noticed that only 999 documents were inserted. After looking at your code, I noticed that you returned a resolve before inserting them. Added the else statement to solve it. This fixed my error.

### CODE REVIEW

**Comment by toymachiner62** [comment]
At first glance this doesn't necessarily seem like the right solution. Can you create a test(s) around this issue?

**Comment by danielmhair** [comment]
I agree. At first glance, this solution doesn't make sense and seems more pointless than helpful, especially if you think about it synchronously. That is why this error took me a while to find. Think about it asynchronously. Here is the code in question:
```
if(contents.length !== 0) {
    db.collection(collection_name).insert(contents, function(err, result) {
        if(err) {
          return reject(err);
        }
        return resolve(result);
  });
}
   
return resolve();
```
So if the file has data, then it will call insert, but because the insert method has a callback, it is going to wait a few seconds (depending on the content size). Because I have a JSON file of 711,000+ lines, the amount of time it takes to finish the insert call, then the program continues onto the next execution line, which is that return resolve(); So the program called insert, then it calls the last line 'return resolve()'.
```
if(contents.length !== 0) { **//In our test case, we have a lot of content, so call insert**
    db.collection(collection_name).insert(contents, function(err, result) { 
        **//NOTE: Insert takes about 20-40 seconds to run insert because of the content length, 
        //             so it never gets to these 4 lines of code, so the program just goes to the next line, 
        //             which is the last line**
        if(err) {
          return reject(err);
        }
        return resolve(result);
  });
}
**//This resolve is called by the time mongo has inserted 999 documents, not the 100,000+ documents**
return resolve();
```
This is the reason why you need else, because we only want the promise to resolve once (either if there is no content or if it inserted the items).

At this moment, I am unable to make a test case, but I will try to create a test case this week, if time allows. Let me know if my explanation makes sense.

**Comment by toymachiner62** [comment]
Ahh thanks that makes sense.

**Comment by toymachiner62** [comment]
Version 2.2.8 published to NPM with this fix.

**Comment by danielmhair** [comment]
Thanks :)

**Pull request merged**
